# spring.application.name=eurekaServerApplication
spring:
   application: 
      name: eurekaServerApplication
server:
   port: 8761
eureka:
   client:
     registerWithEureka: false
     fetchRegistry: false
